### ISSUE TITLE
Is there any way to reduce memory usage?

### ISSUE THREAD

**Issue by skylook** [raulmur/ORB_SLAM2#82]
In my test, there is about 500MB memory occupied by ORB SLAM.  That seems to be unacceptable for mobile phones.
Most of the usage comes from BOW vocabulary and keyframe database I suppose.
Is there any way to reduce the memory usage?

**Comment by raulmur** [comment]
You can create your own vocabulary using the "create" function in Thirdparty/DBoW2/DBoW2/TemplatedVocabulary.h  and then save it. Using a vocabulary of 5 levels instead of 6 will reduce in a factor of 10 the memory without a significant lost in performance. We give some details on how we created the default vocabulary here: http://webdiis.unizar.es/~jdtardos/papers/2014_IEEE_ICRA_Mur_Tardos.pdf

**Comment by weblucas** [comment]
Hi Raul,

Where can I  download the Bovisa dataset?

Thank you

Lucas

**Comment by raulmur** [comment]
http://www.rawseeds.org/rs/datasets/view//7

**Comment by weblucas** [comment]
I tried these torrents, but nobody is sharing this torrents. Do you know
where else I can try to donwload this?

**Comment by raulmur** [comment]
I did not know this was not working... 
Anyway you can use other sequences. For example you could mix the outdoors NewCollege (http://www.robots.ox.ac.uk/NewCollegeData/) and the indoors MIT Stata Center (http://projects.csail.mit.edu/stata/downloads.php)

**Comment by skylook** [comment]
Thanks, that's really helps, I will try that :)

**Comment by realitian** [comment]
Can anybody help me by sharing the recreated vocabulary of 5 levels instead of 6?
