### ISSUE TITLE
Open CV > 2.4.3 not found

### ISSUE THREAD

**Issue by dhrupad-u** [raulmur/ORB_SLAM2#862]
I have installed OpenCV 4.2.0 on Ubuntu platform, but CMake is not able to detect it?

Should I reinstall OpenCV from the source?

Error message:

```
-- Using flag -std=c++11.
CMake Error at CMakeLists.txt:35 (message):
OpenCV > 2.4.3 not found.
```

**Comment by AlejandroSilvestri** [comment]
@dhrupad-u 

ORB-SLAM2 has opencv 3 support.

If you can, try editing [CMakeLists.txt](https://github.com/raulmur/ORB_SLAM2/blob/f2e6f51cdc8d067655d90a78c06261378e07e8f3/CMakeLists.txt#L31) so it look for opencv 4 too.  I believe it is full compatible, because orb-slam2 uses classes and functions (like Mat, KeyPoint and FAST) opencv keeps without changes from 2.4.3 version.

If succeed, please let us know.

**Comment by dhrupad-u** [comment]
It worked!
Thanks!
